// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mall/ent/predicate"
	"mall/ent/psconfig"
	"mall/ent/psstrategy"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePsConfig   = "PsConfig"
	TypePsStrategy = "PsStrategy"
)

// PsConfigMutation represents an operation that mutates the PsConfig nodes in the graph.
type PsConfigMutation struct {
	config
	op              Op
	typ             string
	id              *int
	create_time     *time.Time
	update_time     *time.Time
	ps_id           *int
	addps_id        *int
	ps_scene        *string
	ps_filter       *int
	addps_filter    *int
	ps_message      *int
	addps_message   *int
	ps_event        *int
	addps_event     *int
	ps_feature      *int
	addps_feature   *int
	owner_id        *int
	addowner_id     *int
	managers        *string
	update_user     *int
	addupdate_user  *int
	clearedFields   map[string]struct{}
	strategy        *int
	clearedstrategy bool
	done            bool
	oldValue        func(context.Context) (*PsConfig, error)
	predicates      []predicate.PsConfig
}

var _ ent.Mutation = (*PsConfigMutation)(nil)

// psconfigOption allows management of the mutation configuration using functional options.
type psconfigOption func(*PsConfigMutation)

// newPsConfigMutation creates new mutation for the PsConfig entity.
func newPsConfigMutation(c config, op Op, opts ...psconfigOption) *PsConfigMutation {
	m := &PsConfigMutation{
		config:        c,
		op:            op,
		typ:           TypePsConfig,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPsConfigID sets the ID field of the mutation.
func withPsConfigID(id int) psconfigOption {
	return func(m *PsConfigMutation) {
		var (
			err   error
			once  sync.Once
			value *PsConfig
		)
		m.oldValue = func(ctx context.Context) (*PsConfig, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PsConfig.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPsConfig sets the old PsConfig of the mutation.
func withPsConfig(node *PsConfig) psconfigOption {
	return func(m *PsConfigMutation) {
		m.oldValue = func(context.Context) (*PsConfig, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PsConfigMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PsConfigMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PsConfigMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PsConfigMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PsConfig.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *PsConfigMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *PsConfigMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *PsConfigMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *PsConfigMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *PsConfigMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *PsConfigMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetPsID sets the "ps_id" field.
func (m *PsConfigMutation) SetPsID(i int) {
	m.ps_id = &i
	m.addps_id = nil
}

// PsID returns the value of the "ps_id" field in the mutation.
func (m *PsConfigMutation) PsID() (r int, exists bool) {
	v := m.ps_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPsID returns the old "ps_id" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldPsID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPsID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPsID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPsID: %w", err)
	}
	return oldValue.PsID, nil
}

// AddPsID adds i to the "ps_id" field.
func (m *PsConfigMutation) AddPsID(i int) {
	if m.addps_id != nil {
		*m.addps_id += i
	} else {
		m.addps_id = &i
	}
}

// AddedPsID returns the value that was added to the "ps_id" field in this mutation.
func (m *PsConfigMutation) AddedPsID() (r int, exists bool) {
	v := m.addps_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetPsID resets all changes to the "ps_id" field.
func (m *PsConfigMutation) ResetPsID() {
	m.ps_id = nil
	m.addps_id = nil
}

// SetPsScene sets the "ps_scene" field.
func (m *PsConfigMutation) SetPsScene(s string) {
	m.ps_scene = &s
}

// PsScene returns the value of the "ps_scene" field in the mutation.
func (m *PsConfigMutation) PsScene() (r string, exists bool) {
	v := m.ps_scene
	if v == nil {
		return
	}
	return *v, true
}

// OldPsScene returns the old "ps_scene" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldPsScene(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPsScene is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPsScene requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPsScene: %w", err)
	}
	return oldValue.PsScene, nil
}

// ResetPsScene resets all changes to the "ps_scene" field.
func (m *PsConfigMutation) ResetPsScene() {
	m.ps_scene = nil
}

// SetPsFilter sets the "ps_filter" field.
func (m *PsConfigMutation) SetPsFilter(i int) {
	m.ps_filter = &i
	m.addps_filter = nil
}

// PsFilter returns the value of the "ps_filter" field in the mutation.
func (m *PsConfigMutation) PsFilter() (r int, exists bool) {
	v := m.ps_filter
	if v == nil {
		return
	}
	return *v, true
}

// OldPsFilter returns the old "ps_filter" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldPsFilter(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPsFilter is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPsFilter requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPsFilter: %w", err)
	}
	return oldValue.PsFilter, nil
}

// AddPsFilter adds i to the "ps_filter" field.
func (m *PsConfigMutation) AddPsFilter(i int) {
	if m.addps_filter != nil {
		*m.addps_filter += i
	} else {
		m.addps_filter = &i
	}
}

// AddedPsFilter returns the value that was added to the "ps_filter" field in this mutation.
func (m *PsConfigMutation) AddedPsFilter() (r int, exists bool) {
	v := m.addps_filter
	if v == nil {
		return
	}
	return *v, true
}

// ResetPsFilter resets all changes to the "ps_filter" field.
func (m *PsConfigMutation) ResetPsFilter() {
	m.ps_filter = nil
	m.addps_filter = nil
}

// SetPsMessage sets the "ps_message" field.
func (m *PsConfigMutation) SetPsMessage(i int) {
	m.ps_message = &i
	m.addps_message = nil
}

// PsMessage returns the value of the "ps_message" field in the mutation.
func (m *PsConfigMutation) PsMessage() (r int, exists bool) {
	v := m.ps_message
	if v == nil {
		return
	}
	return *v, true
}

// OldPsMessage returns the old "ps_message" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldPsMessage(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPsMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPsMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPsMessage: %w", err)
	}
	return oldValue.PsMessage, nil
}

// AddPsMessage adds i to the "ps_message" field.
func (m *PsConfigMutation) AddPsMessage(i int) {
	if m.addps_message != nil {
		*m.addps_message += i
	} else {
		m.addps_message = &i
	}
}

// AddedPsMessage returns the value that was added to the "ps_message" field in this mutation.
func (m *PsConfigMutation) AddedPsMessage() (r int, exists bool) {
	v := m.addps_message
	if v == nil {
		return
	}
	return *v, true
}

// ClearPsMessage clears the value of the "ps_message" field.
func (m *PsConfigMutation) ClearPsMessage() {
	m.ps_message = nil
	m.addps_message = nil
	m.clearedFields[psconfig.FieldPsMessage] = struct{}{}
}

// PsMessageCleared returns if the "ps_message" field was cleared in this mutation.
func (m *PsConfigMutation) PsMessageCleared() bool {
	_, ok := m.clearedFields[psconfig.FieldPsMessage]
	return ok
}

// ResetPsMessage resets all changes to the "ps_message" field.
func (m *PsConfigMutation) ResetPsMessage() {
	m.ps_message = nil
	m.addps_message = nil
	delete(m.clearedFields, psconfig.FieldPsMessage)
}

// SetPsEvent sets the "ps_event" field.
func (m *PsConfigMutation) SetPsEvent(i int) {
	m.ps_event = &i
	m.addps_event = nil
}

// PsEvent returns the value of the "ps_event" field in the mutation.
func (m *PsConfigMutation) PsEvent() (r int, exists bool) {
	v := m.ps_event
	if v == nil {
		return
	}
	return *v, true
}

// OldPsEvent returns the old "ps_event" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldPsEvent(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPsEvent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPsEvent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPsEvent: %w", err)
	}
	return oldValue.PsEvent, nil
}

// AddPsEvent adds i to the "ps_event" field.
func (m *PsConfigMutation) AddPsEvent(i int) {
	if m.addps_event != nil {
		*m.addps_event += i
	} else {
		m.addps_event = &i
	}
}

// AddedPsEvent returns the value that was added to the "ps_event" field in this mutation.
func (m *PsConfigMutation) AddedPsEvent() (r int, exists bool) {
	v := m.addps_event
	if v == nil {
		return
	}
	return *v, true
}

// ClearPsEvent clears the value of the "ps_event" field.
func (m *PsConfigMutation) ClearPsEvent() {
	m.ps_event = nil
	m.addps_event = nil
	m.clearedFields[psconfig.FieldPsEvent] = struct{}{}
}

// PsEventCleared returns if the "ps_event" field was cleared in this mutation.
func (m *PsConfigMutation) PsEventCleared() bool {
	_, ok := m.clearedFields[psconfig.FieldPsEvent]
	return ok
}

// ResetPsEvent resets all changes to the "ps_event" field.
func (m *PsConfigMutation) ResetPsEvent() {
	m.ps_event = nil
	m.addps_event = nil
	delete(m.clearedFields, psconfig.FieldPsEvent)
}

// SetPsFeature sets the "ps_feature" field.
func (m *PsConfigMutation) SetPsFeature(i int) {
	m.ps_feature = &i
	m.addps_feature = nil
}

// PsFeature returns the value of the "ps_feature" field in the mutation.
func (m *PsConfigMutation) PsFeature() (r int, exists bool) {
	v := m.ps_feature
	if v == nil {
		return
	}
	return *v, true
}

// OldPsFeature returns the old "ps_feature" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldPsFeature(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPsFeature is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPsFeature requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPsFeature: %w", err)
	}
	return oldValue.PsFeature, nil
}

// AddPsFeature adds i to the "ps_feature" field.
func (m *PsConfigMutation) AddPsFeature(i int) {
	if m.addps_feature != nil {
		*m.addps_feature += i
	} else {
		m.addps_feature = &i
	}
}

// AddedPsFeature returns the value that was added to the "ps_feature" field in this mutation.
func (m *PsConfigMutation) AddedPsFeature() (r int, exists bool) {
	v := m.addps_feature
	if v == nil {
		return
	}
	return *v, true
}

// ClearPsFeature clears the value of the "ps_feature" field.
func (m *PsConfigMutation) ClearPsFeature() {
	m.ps_feature = nil
	m.addps_feature = nil
	m.clearedFields[psconfig.FieldPsFeature] = struct{}{}
}

// PsFeatureCleared returns if the "ps_feature" field was cleared in this mutation.
func (m *PsConfigMutation) PsFeatureCleared() bool {
	_, ok := m.clearedFields[psconfig.FieldPsFeature]
	return ok
}

// ResetPsFeature resets all changes to the "ps_feature" field.
func (m *PsConfigMutation) ResetPsFeature() {
	m.ps_feature = nil
	m.addps_feature = nil
	delete(m.clearedFields, psconfig.FieldPsFeature)
}

// SetPsStrategy sets the "ps_strategy" field.
func (m *PsConfigMutation) SetPsStrategy(i int) {
	m.strategy = &i
}

// PsStrategy returns the value of the "ps_strategy" field in the mutation.
func (m *PsConfigMutation) PsStrategy() (r int, exists bool) {
	v := m.strategy
	if v == nil {
		return
	}
	return *v, true
}

// OldPsStrategy returns the old "ps_strategy" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldPsStrategy(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPsStrategy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPsStrategy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPsStrategy: %w", err)
	}
	return oldValue.PsStrategy, nil
}

// ClearPsStrategy clears the value of the "ps_strategy" field.
func (m *PsConfigMutation) ClearPsStrategy() {
	m.strategy = nil
	m.clearedFields[psconfig.FieldPsStrategy] = struct{}{}
}

// PsStrategyCleared returns if the "ps_strategy" field was cleared in this mutation.
func (m *PsConfigMutation) PsStrategyCleared() bool {
	_, ok := m.clearedFields[psconfig.FieldPsStrategy]
	return ok
}

// ResetPsStrategy resets all changes to the "ps_strategy" field.
func (m *PsConfigMutation) ResetPsStrategy() {
	m.strategy = nil
	delete(m.clearedFields, psconfig.FieldPsStrategy)
}

// SetOwnerID sets the "owner_id" field.
func (m *PsConfigMutation) SetOwnerID(i int) {
	m.owner_id = &i
	m.addowner_id = nil
}

// OwnerID returns the value of the "owner_id" field in the mutation.
func (m *PsConfigMutation) OwnerID() (r int, exists bool) {
	v := m.owner_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOwnerID returns the old "owner_id" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldOwnerID(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwnerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwnerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwnerID: %w", err)
	}
	return oldValue.OwnerID, nil
}

// AddOwnerID adds i to the "owner_id" field.
func (m *PsConfigMutation) AddOwnerID(i int) {
	if m.addowner_id != nil {
		*m.addowner_id += i
	} else {
		m.addowner_id = &i
	}
}

// AddedOwnerID returns the value that was added to the "owner_id" field in this mutation.
func (m *PsConfigMutation) AddedOwnerID() (r int, exists bool) {
	v := m.addowner_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearOwnerID clears the value of the "owner_id" field.
func (m *PsConfigMutation) ClearOwnerID() {
	m.owner_id = nil
	m.addowner_id = nil
	m.clearedFields[psconfig.FieldOwnerID] = struct{}{}
}

// OwnerIDCleared returns if the "owner_id" field was cleared in this mutation.
func (m *PsConfigMutation) OwnerIDCleared() bool {
	_, ok := m.clearedFields[psconfig.FieldOwnerID]
	return ok
}

// ResetOwnerID resets all changes to the "owner_id" field.
func (m *PsConfigMutation) ResetOwnerID() {
	m.owner_id = nil
	m.addowner_id = nil
	delete(m.clearedFields, psconfig.FieldOwnerID)
}

// SetManagers sets the "managers" field.
func (m *PsConfigMutation) SetManagers(s string) {
	m.managers = &s
}

// Managers returns the value of the "managers" field in the mutation.
func (m *PsConfigMutation) Managers() (r string, exists bool) {
	v := m.managers
	if v == nil {
		return
	}
	return *v, true
}

// OldManagers returns the old "managers" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldManagers(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldManagers is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldManagers requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldManagers: %w", err)
	}
	return oldValue.Managers, nil
}

// ClearManagers clears the value of the "managers" field.
func (m *PsConfigMutation) ClearManagers() {
	m.managers = nil
	m.clearedFields[psconfig.FieldManagers] = struct{}{}
}

// ManagersCleared returns if the "managers" field was cleared in this mutation.
func (m *PsConfigMutation) ManagersCleared() bool {
	_, ok := m.clearedFields[psconfig.FieldManagers]
	return ok
}

// ResetManagers resets all changes to the "managers" field.
func (m *PsConfigMutation) ResetManagers() {
	m.managers = nil
	delete(m.clearedFields, psconfig.FieldManagers)
}

// SetUpdateUser sets the "update_user" field.
func (m *PsConfigMutation) SetUpdateUser(i int) {
	m.update_user = &i
	m.addupdate_user = nil
}

// UpdateUser returns the value of the "update_user" field in the mutation.
func (m *PsConfigMutation) UpdateUser() (r int, exists bool) {
	v := m.update_user
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateUser returns the old "update_user" field's value of the PsConfig entity.
// If the PsConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsConfigMutation) OldUpdateUser(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateUser is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateUser requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateUser: %w", err)
	}
	return oldValue.UpdateUser, nil
}

// AddUpdateUser adds i to the "update_user" field.
func (m *PsConfigMutation) AddUpdateUser(i int) {
	if m.addupdate_user != nil {
		*m.addupdate_user += i
	} else {
		m.addupdate_user = &i
	}
}

// AddedUpdateUser returns the value that was added to the "update_user" field in this mutation.
func (m *PsConfigMutation) AddedUpdateUser() (r int, exists bool) {
	v := m.addupdate_user
	if v == nil {
		return
	}
	return *v, true
}

// ClearUpdateUser clears the value of the "update_user" field.
func (m *PsConfigMutation) ClearUpdateUser() {
	m.update_user = nil
	m.addupdate_user = nil
	m.clearedFields[psconfig.FieldUpdateUser] = struct{}{}
}

// UpdateUserCleared returns if the "update_user" field was cleared in this mutation.
func (m *PsConfigMutation) UpdateUserCleared() bool {
	_, ok := m.clearedFields[psconfig.FieldUpdateUser]
	return ok
}

// ResetUpdateUser resets all changes to the "update_user" field.
func (m *PsConfigMutation) ResetUpdateUser() {
	m.update_user = nil
	m.addupdate_user = nil
	delete(m.clearedFields, psconfig.FieldUpdateUser)
}

// SetStrategyID sets the "strategy" edge to the PsStrategy entity by id.
func (m *PsConfigMutation) SetStrategyID(id int) {
	m.strategy = &id
}

// ClearStrategy clears the "strategy" edge to the PsStrategy entity.
func (m *PsConfigMutation) ClearStrategy() {
	m.clearedstrategy = true
	m.clearedFields[psconfig.FieldPsStrategy] = struct{}{}
}

// StrategyCleared reports if the "strategy" edge to the PsStrategy entity was cleared.
func (m *PsConfigMutation) StrategyCleared() bool {
	return m.PsStrategyCleared() || m.clearedstrategy
}

// StrategyID returns the "strategy" edge ID in the mutation.
func (m *PsConfigMutation) StrategyID() (id int, exists bool) {
	if m.strategy != nil {
		return *m.strategy, true
	}
	return
}

// StrategyIDs returns the "strategy" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// StrategyID instead. It exists only for internal usage by the builders.
func (m *PsConfigMutation) StrategyIDs() (ids []int) {
	if id := m.strategy; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetStrategy resets all changes to the "strategy" edge.
func (m *PsConfigMutation) ResetStrategy() {
	m.strategy = nil
	m.clearedstrategy = false
}

// Where appends a list predicates to the PsConfigMutation builder.
func (m *PsConfigMutation) Where(ps ...predicate.PsConfig) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PsConfigMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PsConfigMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PsConfig, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PsConfigMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PsConfigMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PsConfig).
func (m *PsConfigMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PsConfigMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.create_time != nil {
		fields = append(fields, psconfig.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, psconfig.FieldUpdateTime)
	}
	if m.ps_id != nil {
		fields = append(fields, psconfig.FieldPsID)
	}
	if m.ps_scene != nil {
		fields = append(fields, psconfig.FieldPsScene)
	}
	if m.ps_filter != nil {
		fields = append(fields, psconfig.FieldPsFilter)
	}
	if m.ps_message != nil {
		fields = append(fields, psconfig.FieldPsMessage)
	}
	if m.ps_event != nil {
		fields = append(fields, psconfig.FieldPsEvent)
	}
	if m.ps_feature != nil {
		fields = append(fields, psconfig.FieldPsFeature)
	}
	if m.strategy != nil {
		fields = append(fields, psconfig.FieldPsStrategy)
	}
	if m.owner_id != nil {
		fields = append(fields, psconfig.FieldOwnerID)
	}
	if m.managers != nil {
		fields = append(fields, psconfig.FieldManagers)
	}
	if m.update_user != nil {
		fields = append(fields, psconfig.FieldUpdateUser)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PsConfigMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case psconfig.FieldCreateTime:
		return m.CreateTime()
	case psconfig.FieldUpdateTime:
		return m.UpdateTime()
	case psconfig.FieldPsID:
		return m.PsID()
	case psconfig.FieldPsScene:
		return m.PsScene()
	case psconfig.FieldPsFilter:
		return m.PsFilter()
	case psconfig.FieldPsMessage:
		return m.PsMessage()
	case psconfig.FieldPsEvent:
		return m.PsEvent()
	case psconfig.FieldPsFeature:
		return m.PsFeature()
	case psconfig.FieldPsStrategy:
		return m.PsStrategy()
	case psconfig.FieldOwnerID:
		return m.OwnerID()
	case psconfig.FieldManagers:
		return m.Managers()
	case psconfig.FieldUpdateUser:
		return m.UpdateUser()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PsConfigMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case psconfig.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case psconfig.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case psconfig.FieldPsID:
		return m.OldPsID(ctx)
	case psconfig.FieldPsScene:
		return m.OldPsScene(ctx)
	case psconfig.FieldPsFilter:
		return m.OldPsFilter(ctx)
	case psconfig.FieldPsMessage:
		return m.OldPsMessage(ctx)
	case psconfig.FieldPsEvent:
		return m.OldPsEvent(ctx)
	case psconfig.FieldPsFeature:
		return m.OldPsFeature(ctx)
	case psconfig.FieldPsStrategy:
		return m.OldPsStrategy(ctx)
	case psconfig.FieldOwnerID:
		return m.OldOwnerID(ctx)
	case psconfig.FieldManagers:
		return m.OldManagers(ctx)
	case psconfig.FieldUpdateUser:
		return m.OldUpdateUser(ctx)
	}
	return nil, fmt.Errorf("unknown PsConfig field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PsConfigMutation) SetField(name string, value ent.Value) error {
	switch name {
	case psconfig.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case psconfig.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case psconfig.FieldPsID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPsID(v)
		return nil
	case psconfig.FieldPsScene:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPsScene(v)
		return nil
	case psconfig.FieldPsFilter:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPsFilter(v)
		return nil
	case psconfig.FieldPsMessage:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPsMessage(v)
		return nil
	case psconfig.FieldPsEvent:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPsEvent(v)
		return nil
	case psconfig.FieldPsFeature:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPsFeature(v)
		return nil
	case psconfig.FieldPsStrategy:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPsStrategy(v)
		return nil
	case psconfig.FieldOwnerID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwnerID(v)
		return nil
	case psconfig.FieldManagers:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManagers(v)
		return nil
	case psconfig.FieldUpdateUser:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateUser(v)
		return nil
	}
	return fmt.Errorf("unknown PsConfig field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PsConfigMutation) AddedFields() []string {
	var fields []string
	if m.addps_id != nil {
		fields = append(fields, psconfig.FieldPsID)
	}
	if m.addps_filter != nil {
		fields = append(fields, psconfig.FieldPsFilter)
	}
	if m.addps_message != nil {
		fields = append(fields, psconfig.FieldPsMessage)
	}
	if m.addps_event != nil {
		fields = append(fields, psconfig.FieldPsEvent)
	}
	if m.addps_feature != nil {
		fields = append(fields, psconfig.FieldPsFeature)
	}
	if m.addowner_id != nil {
		fields = append(fields, psconfig.FieldOwnerID)
	}
	if m.addupdate_user != nil {
		fields = append(fields, psconfig.FieldUpdateUser)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PsConfigMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case psconfig.FieldPsID:
		return m.AddedPsID()
	case psconfig.FieldPsFilter:
		return m.AddedPsFilter()
	case psconfig.FieldPsMessage:
		return m.AddedPsMessage()
	case psconfig.FieldPsEvent:
		return m.AddedPsEvent()
	case psconfig.FieldPsFeature:
		return m.AddedPsFeature()
	case psconfig.FieldOwnerID:
		return m.AddedOwnerID()
	case psconfig.FieldUpdateUser:
		return m.AddedUpdateUser()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PsConfigMutation) AddField(name string, value ent.Value) error {
	switch name {
	case psconfig.FieldPsID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPsID(v)
		return nil
	case psconfig.FieldPsFilter:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPsFilter(v)
		return nil
	case psconfig.FieldPsMessage:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPsMessage(v)
		return nil
	case psconfig.FieldPsEvent:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPsEvent(v)
		return nil
	case psconfig.FieldPsFeature:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPsFeature(v)
		return nil
	case psconfig.FieldOwnerID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOwnerID(v)
		return nil
	case psconfig.FieldUpdateUser:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdateUser(v)
		return nil
	}
	return fmt.Errorf("unknown PsConfig numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PsConfigMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(psconfig.FieldPsMessage) {
		fields = append(fields, psconfig.FieldPsMessage)
	}
	if m.FieldCleared(psconfig.FieldPsEvent) {
		fields = append(fields, psconfig.FieldPsEvent)
	}
	if m.FieldCleared(psconfig.FieldPsFeature) {
		fields = append(fields, psconfig.FieldPsFeature)
	}
	if m.FieldCleared(psconfig.FieldPsStrategy) {
		fields = append(fields, psconfig.FieldPsStrategy)
	}
	if m.FieldCleared(psconfig.FieldOwnerID) {
		fields = append(fields, psconfig.FieldOwnerID)
	}
	if m.FieldCleared(psconfig.FieldManagers) {
		fields = append(fields, psconfig.FieldManagers)
	}
	if m.FieldCleared(psconfig.FieldUpdateUser) {
		fields = append(fields, psconfig.FieldUpdateUser)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PsConfigMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PsConfigMutation) ClearField(name string) error {
	switch name {
	case psconfig.FieldPsMessage:
		m.ClearPsMessage()
		return nil
	case psconfig.FieldPsEvent:
		m.ClearPsEvent()
		return nil
	case psconfig.FieldPsFeature:
		m.ClearPsFeature()
		return nil
	case psconfig.FieldPsStrategy:
		m.ClearPsStrategy()
		return nil
	case psconfig.FieldOwnerID:
		m.ClearOwnerID()
		return nil
	case psconfig.FieldManagers:
		m.ClearManagers()
		return nil
	case psconfig.FieldUpdateUser:
		m.ClearUpdateUser()
		return nil
	}
	return fmt.Errorf("unknown PsConfig nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PsConfigMutation) ResetField(name string) error {
	switch name {
	case psconfig.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case psconfig.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case psconfig.FieldPsID:
		m.ResetPsID()
		return nil
	case psconfig.FieldPsScene:
		m.ResetPsScene()
		return nil
	case psconfig.FieldPsFilter:
		m.ResetPsFilter()
		return nil
	case psconfig.FieldPsMessage:
		m.ResetPsMessage()
		return nil
	case psconfig.FieldPsEvent:
		m.ResetPsEvent()
		return nil
	case psconfig.FieldPsFeature:
		m.ResetPsFeature()
		return nil
	case psconfig.FieldPsStrategy:
		m.ResetPsStrategy()
		return nil
	case psconfig.FieldOwnerID:
		m.ResetOwnerID()
		return nil
	case psconfig.FieldManagers:
		m.ResetManagers()
		return nil
	case psconfig.FieldUpdateUser:
		m.ResetUpdateUser()
		return nil
	}
	return fmt.Errorf("unknown PsConfig field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PsConfigMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.strategy != nil {
		edges = append(edges, psconfig.EdgeStrategy)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PsConfigMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case psconfig.EdgeStrategy:
		if id := m.strategy; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PsConfigMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PsConfigMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PsConfigMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedstrategy {
		edges = append(edges, psconfig.EdgeStrategy)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PsConfigMutation) EdgeCleared(name string) bool {
	switch name {
	case psconfig.EdgeStrategy:
		return m.clearedstrategy
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PsConfigMutation) ClearEdge(name string) error {
	switch name {
	case psconfig.EdgeStrategy:
		m.ClearStrategy()
		return nil
	}
	return fmt.Errorf("unknown PsConfig unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PsConfigMutation) ResetEdge(name string) error {
	switch name {
	case psconfig.EdgeStrategy:
		m.ResetStrategy()
		return nil
	}
	return fmt.Errorf("unknown PsConfig edge %s", name)
}

// PsStrategyMutation represents an operation that mutates the PsStrategy nodes in the graph.
type PsStrategyMutation struct {
	config
	op             Op
	typ            string
	id             *int
	create_time    *time.Time
	update_time    *time.Time
	owner          *int
	addowner       *int
	script_content *string
	is_delete      *int
	addis_delete   *int
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*PsStrategy, error)
	predicates     []predicate.PsStrategy
}

var _ ent.Mutation = (*PsStrategyMutation)(nil)

// psstrategyOption allows management of the mutation configuration using functional options.
type psstrategyOption func(*PsStrategyMutation)

// newPsStrategyMutation creates new mutation for the PsStrategy entity.
func newPsStrategyMutation(c config, op Op, opts ...psstrategyOption) *PsStrategyMutation {
	m := &PsStrategyMutation{
		config:        c,
		op:            op,
		typ:           TypePsStrategy,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPsStrategyID sets the ID field of the mutation.
func withPsStrategyID(id int) psstrategyOption {
	return func(m *PsStrategyMutation) {
		var (
			err   error
			once  sync.Once
			value *PsStrategy
		)
		m.oldValue = func(ctx context.Context) (*PsStrategy, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PsStrategy.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPsStrategy sets the old PsStrategy of the mutation.
func withPsStrategy(node *PsStrategy) psstrategyOption {
	return func(m *PsStrategyMutation) {
		m.oldValue = func(context.Context) (*PsStrategy, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PsStrategyMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PsStrategyMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PsStrategy entities.
func (m *PsStrategyMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PsStrategyMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PsStrategyMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PsStrategy.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *PsStrategyMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *PsStrategyMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the PsStrategy entity.
// If the PsStrategy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsStrategyMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *PsStrategyMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *PsStrategyMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *PsStrategyMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the PsStrategy entity.
// If the PsStrategy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsStrategyMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *PsStrategyMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetOwner sets the "owner" field.
func (m *PsStrategyMutation) SetOwner(i int) {
	m.owner = &i
	m.addowner = nil
}

// Owner returns the value of the "owner" field in the mutation.
func (m *PsStrategyMutation) Owner() (r int, exists bool) {
	v := m.owner
	if v == nil {
		return
	}
	return *v, true
}

// OldOwner returns the old "owner" field's value of the PsStrategy entity.
// If the PsStrategy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsStrategyMutation) OldOwner(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwner is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwner requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwner: %w", err)
	}
	return oldValue.Owner, nil
}

// AddOwner adds i to the "owner" field.
func (m *PsStrategyMutation) AddOwner(i int) {
	if m.addowner != nil {
		*m.addowner += i
	} else {
		m.addowner = &i
	}
}

// AddedOwner returns the value that was added to the "owner" field in this mutation.
func (m *PsStrategyMutation) AddedOwner() (r int, exists bool) {
	v := m.addowner
	if v == nil {
		return
	}
	return *v, true
}

// ResetOwner resets all changes to the "owner" field.
func (m *PsStrategyMutation) ResetOwner() {
	m.owner = nil
	m.addowner = nil
}

// SetScriptContent sets the "script_content" field.
func (m *PsStrategyMutation) SetScriptContent(s string) {
	m.script_content = &s
}

// ScriptContent returns the value of the "script_content" field in the mutation.
func (m *PsStrategyMutation) ScriptContent() (r string, exists bool) {
	v := m.script_content
	if v == nil {
		return
	}
	return *v, true
}

// OldScriptContent returns the old "script_content" field's value of the PsStrategy entity.
// If the PsStrategy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsStrategyMutation) OldScriptContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScriptContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScriptContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScriptContent: %w", err)
	}
	return oldValue.ScriptContent, nil
}

// ResetScriptContent resets all changes to the "script_content" field.
func (m *PsStrategyMutation) ResetScriptContent() {
	m.script_content = nil
}

// SetIsDelete sets the "is_delete" field.
func (m *PsStrategyMutation) SetIsDelete(i int) {
	m.is_delete = &i
	m.addis_delete = nil
}

// IsDelete returns the value of the "is_delete" field in the mutation.
func (m *PsStrategyMutation) IsDelete() (r int, exists bool) {
	v := m.is_delete
	if v == nil {
		return
	}
	return *v, true
}

// OldIsDelete returns the old "is_delete" field's value of the PsStrategy entity.
// If the PsStrategy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PsStrategyMutation) OldIsDelete(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsDelete is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsDelete requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsDelete: %w", err)
	}
	return oldValue.IsDelete, nil
}

// AddIsDelete adds i to the "is_delete" field.
func (m *PsStrategyMutation) AddIsDelete(i int) {
	if m.addis_delete != nil {
		*m.addis_delete += i
	} else {
		m.addis_delete = &i
	}
}

// AddedIsDelete returns the value that was added to the "is_delete" field in this mutation.
func (m *PsStrategyMutation) AddedIsDelete() (r int, exists bool) {
	v := m.addis_delete
	if v == nil {
		return
	}
	return *v, true
}

// ResetIsDelete resets all changes to the "is_delete" field.
func (m *PsStrategyMutation) ResetIsDelete() {
	m.is_delete = nil
	m.addis_delete = nil
}

// Where appends a list predicates to the PsStrategyMutation builder.
func (m *PsStrategyMutation) Where(ps ...predicate.PsStrategy) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PsStrategyMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PsStrategyMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PsStrategy, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PsStrategyMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PsStrategyMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PsStrategy).
func (m *PsStrategyMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PsStrategyMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.create_time != nil {
		fields = append(fields, psstrategy.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, psstrategy.FieldUpdateTime)
	}
	if m.owner != nil {
		fields = append(fields, psstrategy.FieldOwner)
	}
	if m.script_content != nil {
		fields = append(fields, psstrategy.FieldScriptContent)
	}
	if m.is_delete != nil {
		fields = append(fields, psstrategy.FieldIsDelete)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PsStrategyMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case psstrategy.FieldCreateTime:
		return m.CreateTime()
	case psstrategy.FieldUpdateTime:
		return m.UpdateTime()
	case psstrategy.FieldOwner:
		return m.Owner()
	case psstrategy.FieldScriptContent:
		return m.ScriptContent()
	case psstrategy.FieldIsDelete:
		return m.IsDelete()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PsStrategyMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case psstrategy.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case psstrategy.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case psstrategy.FieldOwner:
		return m.OldOwner(ctx)
	case psstrategy.FieldScriptContent:
		return m.OldScriptContent(ctx)
	case psstrategy.FieldIsDelete:
		return m.OldIsDelete(ctx)
	}
	return nil, fmt.Errorf("unknown PsStrategy field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PsStrategyMutation) SetField(name string, value ent.Value) error {
	switch name {
	case psstrategy.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case psstrategy.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case psstrategy.FieldOwner:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwner(v)
		return nil
	case psstrategy.FieldScriptContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScriptContent(v)
		return nil
	case psstrategy.FieldIsDelete:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsDelete(v)
		return nil
	}
	return fmt.Errorf("unknown PsStrategy field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PsStrategyMutation) AddedFields() []string {
	var fields []string
	if m.addowner != nil {
		fields = append(fields, psstrategy.FieldOwner)
	}
	if m.addis_delete != nil {
		fields = append(fields, psstrategy.FieldIsDelete)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PsStrategyMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case psstrategy.FieldOwner:
		return m.AddedOwner()
	case psstrategy.FieldIsDelete:
		return m.AddedIsDelete()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PsStrategyMutation) AddField(name string, value ent.Value) error {
	switch name {
	case psstrategy.FieldOwner:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOwner(v)
		return nil
	case psstrategy.FieldIsDelete:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddIsDelete(v)
		return nil
	}
	return fmt.Errorf("unknown PsStrategy numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PsStrategyMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PsStrategyMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PsStrategyMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PsStrategy nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PsStrategyMutation) ResetField(name string) error {
	switch name {
	case psstrategy.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case psstrategy.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case psstrategy.FieldOwner:
		m.ResetOwner()
		return nil
	case psstrategy.FieldScriptContent:
		m.ResetScriptContent()
		return nil
	case psstrategy.FieldIsDelete:
		m.ResetIsDelete()
		return nil
	}
	return fmt.Errorf("unknown PsStrategy field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PsStrategyMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PsStrategyMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PsStrategyMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PsStrategyMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PsStrategyMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PsStrategyMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PsStrategyMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PsStrategy unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PsStrategyMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PsStrategy edge %s", name)
}
