// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mall/ent/predicate"
	"mall/ent/psconfig"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PsConfigUpdate is the builder for updating PsConfig entities.
type PsConfigUpdate struct {
	config
	hooks    []Hook
	mutation *PsConfigMutation
}

// Where appends a list predicates to the PsConfigUpdate builder.
func (pcu *PsConfigUpdate) Where(ps ...predicate.PsConfig) *PsConfigUpdate {
	pcu.mutation.Where(ps...)
	return pcu
}

// SetUpdateTime sets the "update_time" field.
func (pcu *PsConfigUpdate) SetUpdateTime(t time.Time) *PsConfigUpdate {
	pcu.mutation.SetUpdateTime(t)
	return pcu
}

// SetPsScene sets the "ps_scene" field.
func (pcu *PsConfigUpdate) SetPsScene(s string) *PsConfigUpdate {
	pcu.mutation.SetPsScene(s)
	return pcu
}

// SetNillablePsScene sets the "ps_scene" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillablePsScene(s *string) *PsConfigUpdate {
	if s != nil {
		pcu.SetPsScene(*s)
	}
	return pcu
}

// SetPsFilter sets the "ps_filter" field.
func (pcu *PsConfigUpdate) SetPsFilter(i int) *PsConfigUpdate {
	pcu.mutation.ResetPsFilter()
	pcu.mutation.SetPsFilter(i)
	return pcu
}

// SetNillablePsFilter sets the "ps_filter" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillablePsFilter(i *int) *PsConfigUpdate {
	if i != nil {
		pcu.SetPsFilter(*i)
	}
	return pcu
}

// AddPsFilter adds i to the "ps_filter" field.
func (pcu *PsConfigUpdate) AddPsFilter(i int) *PsConfigUpdate {
	pcu.mutation.AddPsFilter(i)
	return pcu
}

// SetPsMessage sets the "ps_message" field.
func (pcu *PsConfigUpdate) SetPsMessage(i int) *PsConfigUpdate {
	pcu.mutation.ResetPsMessage()
	pcu.mutation.SetPsMessage(i)
	return pcu
}

// SetNillablePsMessage sets the "ps_message" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillablePsMessage(i *int) *PsConfigUpdate {
	if i != nil {
		pcu.SetPsMessage(*i)
	}
	return pcu
}

// AddPsMessage adds i to the "ps_message" field.
func (pcu *PsConfigUpdate) AddPsMessage(i int) *PsConfigUpdate {
	pcu.mutation.AddPsMessage(i)
	return pcu
}

// ClearPsMessage clears the value of the "ps_message" field.
func (pcu *PsConfigUpdate) ClearPsMessage() *PsConfigUpdate {
	pcu.mutation.ClearPsMessage()
	return pcu
}

// SetPsEvent sets the "ps_event" field.
func (pcu *PsConfigUpdate) SetPsEvent(i int) *PsConfigUpdate {
	pcu.mutation.ResetPsEvent()
	pcu.mutation.SetPsEvent(i)
	return pcu
}

// SetNillablePsEvent sets the "ps_event" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillablePsEvent(i *int) *PsConfigUpdate {
	if i != nil {
		pcu.SetPsEvent(*i)
	}
	return pcu
}

// AddPsEvent adds i to the "ps_event" field.
func (pcu *PsConfigUpdate) AddPsEvent(i int) *PsConfigUpdate {
	pcu.mutation.AddPsEvent(i)
	return pcu
}

// ClearPsEvent clears the value of the "ps_event" field.
func (pcu *PsConfigUpdate) ClearPsEvent() *PsConfigUpdate {
	pcu.mutation.ClearPsEvent()
	return pcu
}

// SetPsFeature sets the "ps_feature" field.
func (pcu *PsConfigUpdate) SetPsFeature(i int) *PsConfigUpdate {
	pcu.mutation.ResetPsFeature()
	pcu.mutation.SetPsFeature(i)
	return pcu
}

// SetNillablePsFeature sets the "ps_feature" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillablePsFeature(i *int) *PsConfigUpdate {
	if i != nil {
		pcu.SetPsFeature(*i)
	}
	return pcu
}

// AddPsFeature adds i to the "ps_feature" field.
func (pcu *PsConfigUpdate) AddPsFeature(i int) *PsConfigUpdate {
	pcu.mutation.AddPsFeature(i)
	return pcu
}

// ClearPsFeature clears the value of the "ps_feature" field.
func (pcu *PsConfigUpdate) ClearPsFeature() *PsConfigUpdate {
	pcu.mutation.ClearPsFeature()
	return pcu
}

// SetPsStrategy sets the "ps_strategy" field.
func (pcu *PsConfigUpdate) SetPsStrategy(i int) *PsConfigUpdate {
	pcu.mutation.ResetPsStrategy()
	pcu.mutation.SetPsStrategy(i)
	return pcu
}

// SetNillablePsStrategy sets the "ps_strategy" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillablePsStrategy(i *int) *PsConfigUpdate {
	if i != nil {
		pcu.SetPsStrategy(*i)
	}
	return pcu
}

// AddPsStrategy adds i to the "ps_strategy" field.
func (pcu *PsConfigUpdate) AddPsStrategy(i int) *PsConfigUpdate {
	pcu.mutation.AddPsStrategy(i)
	return pcu
}

// ClearPsStrategy clears the value of the "ps_strategy" field.
func (pcu *PsConfigUpdate) ClearPsStrategy() *PsConfigUpdate {
	pcu.mutation.ClearPsStrategy()
	return pcu
}

// SetOwnerID sets the "owner_id" field.
func (pcu *PsConfigUpdate) SetOwnerID(i int) *PsConfigUpdate {
	pcu.mutation.ResetOwnerID()
	pcu.mutation.SetOwnerID(i)
	return pcu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillableOwnerID(i *int) *PsConfigUpdate {
	if i != nil {
		pcu.SetOwnerID(*i)
	}
	return pcu
}

// AddOwnerID adds i to the "owner_id" field.
func (pcu *PsConfigUpdate) AddOwnerID(i int) *PsConfigUpdate {
	pcu.mutation.AddOwnerID(i)
	return pcu
}

// ClearOwnerID clears the value of the "owner_id" field.
func (pcu *PsConfigUpdate) ClearOwnerID() *PsConfigUpdate {
	pcu.mutation.ClearOwnerID()
	return pcu
}

// SetManagers sets the "managers" field.
func (pcu *PsConfigUpdate) SetManagers(s string) *PsConfigUpdate {
	pcu.mutation.SetManagers(s)
	return pcu
}

// SetNillableManagers sets the "managers" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillableManagers(s *string) *PsConfigUpdate {
	if s != nil {
		pcu.SetManagers(*s)
	}
	return pcu
}

// ClearManagers clears the value of the "managers" field.
func (pcu *PsConfigUpdate) ClearManagers() *PsConfigUpdate {
	pcu.mutation.ClearManagers()
	return pcu
}

// SetUpdateUser sets the "update_user" field.
func (pcu *PsConfigUpdate) SetUpdateUser(i int) *PsConfigUpdate {
	pcu.mutation.ResetUpdateUser()
	pcu.mutation.SetUpdateUser(i)
	return pcu
}

// SetNillableUpdateUser sets the "update_user" field if the given value is not nil.
func (pcu *PsConfigUpdate) SetNillableUpdateUser(i *int) *PsConfigUpdate {
	if i != nil {
		pcu.SetUpdateUser(*i)
	}
	return pcu
}

// AddUpdateUser adds i to the "update_user" field.
func (pcu *PsConfigUpdate) AddUpdateUser(i int) *PsConfigUpdate {
	pcu.mutation.AddUpdateUser(i)
	return pcu
}

// ClearUpdateUser clears the value of the "update_user" field.
func (pcu *PsConfigUpdate) ClearUpdateUser() *PsConfigUpdate {
	pcu.mutation.ClearUpdateUser()
	return pcu
}

// Mutation returns the PsConfigMutation object of the builder.
func (pcu *PsConfigUpdate) Mutation() *PsConfigMutation {
	return pcu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pcu *PsConfigUpdate) Save(ctx context.Context) (int, error) {
	pcu.defaults()
	return withHooks(ctx, pcu.sqlSave, pcu.mutation, pcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pcu *PsConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := pcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pcu *PsConfigUpdate) Exec(ctx context.Context) error {
	_, err := pcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcu *PsConfigUpdate) ExecX(ctx context.Context) {
	if err := pcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcu *PsConfigUpdate) defaults() {
	if _, ok := pcu.mutation.UpdateTime(); !ok {
		v := psconfig.UpdateDefaultUpdateTime()
		pcu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcu *PsConfigUpdate) check() error {
	if v, ok := pcu.mutation.PsScene(); ok {
		if err := psconfig.PsSceneValidator(v); err != nil {
			return &ValidationError{Name: "ps_scene", err: fmt.Errorf(`ent: validator failed for field "PsConfig.ps_scene": %w`, err)}
		}
	}
	return nil
}

func (pcu *PsConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pcu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(psconfig.Table, psconfig.Columns, sqlgraph.NewFieldSpec(psconfig.FieldID, field.TypeInt))
	if ps := pcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcu.mutation.UpdateTime(); ok {
		_spec.SetField(psconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pcu.mutation.PsScene(); ok {
		_spec.SetField(psconfig.FieldPsScene, field.TypeString, value)
	}
	if value, ok := pcu.mutation.PsFilter(); ok {
		_spec.SetField(psconfig.FieldPsFilter, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.AddedPsFilter(); ok {
		_spec.AddField(psconfig.FieldPsFilter, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.PsMessage(); ok {
		_spec.SetField(psconfig.FieldPsMessage, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.AddedPsMessage(); ok {
		_spec.AddField(psconfig.FieldPsMessage, field.TypeInt, value)
	}
	if pcu.mutation.PsMessageCleared() {
		_spec.ClearField(psconfig.FieldPsMessage, field.TypeInt)
	}
	if value, ok := pcu.mutation.PsEvent(); ok {
		_spec.SetField(psconfig.FieldPsEvent, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.AddedPsEvent(); ok {
		_spec.AddField(psconfig.FieldPsEvent, field.TypeInt, value)
	}
	if pcu.mutation.PsEventCleared() {
		_spec.ClearField(psconfig.FieldPsEvent, field.TypeInt)
	}
	if value, ok := pcu.mutation.PsFeature(); ok {
		_spec.SetField(psconfig.FieldPsFeature, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.AddedPsFeature(); ok {
		_spec.AddField(psconfig.FieldPsFeature, field.TypeInt, value)
	}
	if pcu.mutation.PsFeatureCleared() {
		_spec.ClearField(psconfig.FieldPsFeature, field.TypeInt)
	}
	if value, ok := pcu.mutation.PsStrategy(); ok {
		_spec.SetField(psconfig.FieldPsStrategy, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.AddedPsStrategy(); ok {
		_spec.AddField(psconfig.FieldPsStrategy, field.TypeInt, value)
	}
	if pcu.mutation.PsStrategyCleared() {
		_spec.ClearField(psconfig.FieldPsStrategy, field.TypeInt)
	}
	if value, ok := pcu.mutation.OwnerID(); ok {
		_spec.SetField(psconfig.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.AddedOwnerID(); ok {
		_spec.AddField(psconfig.FieldOwnerID, field.TypeInt, value)
	}
	if pcu.mutation.OwnerIDCleared() {
		_spec.ClearField(psconfig.FieldOwnerID, field.TypeInt)
	}
	if value, ok := pcu.mutation.Managers(); ok {
		_spec.SetField(psconfig.FieldManagers, field.TypeString, value)
	}
	if pcu.mutation.ManagersCleared() {
		_spec.ClearField(psconfig.FieldManagers, field.TypeString)
	}
	if value, ok := pcu.mutation.UpdateUser(); ok {
		_spec.SetField(psconfig.FieldUpdateUser, field.TypeInt, value)
	}
	if value, ok := pcu.mutation.AddedUpdateUser(); ok {
		_spec.AddField(psconfig.FieldUpdateUser, field.TypeInt, value)
	}
	if pcu.mutation.UpdateUserCleared() {
		_spec.ClearField(psconfig.FieldUpdateUser, field.TypeInt)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{psconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pcu.mutation.done = true
	return n, nil
}

// PsConfigUpdateOne is the builder for updating a single PsConfig entity.
type PsConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PsConfigMutation
}

// SetUpdateTime sets the "update_time" field.
func (pcuo *PsConfigUpdateOne) SetUpdateTime(t time.Time) *PsConfigUpdateOne {
	pcuo.mutation.SetUpdateTime(t)
	return pcuo
}

// SetPsScene sets the "ps_scene" field.
func (pcuo *PsConfigUpdateOne) SetPsScene(s string) *PsConfigUpdateOne {
	pcuo.mutation.SetPsScene(s)
	return pcuo
}

// SetNillablePsScene sets the "ps_scene" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillablePsScene(s *string) *PsConfigUpdateOne {
	if s != nil {
		pcuo.SetPsScene(*s)
	}
	return pcuo
}

// SetPsFilter sets the "ps_filter" field.
func (pcuo *PsConfigUpdateOne) SetPsFilter(i int) *PsConfigUpdateOne {
	pcuo.mutation.ResetPsFilter()
	pcuo.mutation.SetPsFilter(i)
	return pcuo
}

// SetNillablePsFilter sets the "ps_filter" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillablePsFilter(i *int) *PsConfigUpdateOne {
	if i != nil {
		pcuo.SetPsFilter(*i)
	}
	return pcuo
}

// AddPsFilter adds i to the "ps_filter" field.
func (pcuo *PsConfigUpdateOne) AddPsFilter(i int) *PsConfigUpdateOne {
	pcuo.mutation.AddPsFilter(i)
	return pcuo
}

// SetPsMessage sets the "ps_message" field.
func (pcuo *PsConfigUpdateOne) SetPsMessage(i int) *PsConfigUpdateOne {
	pcuo.mutation.ResetPsMessage()
	pcuo.mutation.SetPsMessage(i)
	return pcuo
}

// SetNillablePsMessage sets the "ps_message" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillablePsMessage(i *int) *PsConfigUpdateOne {
	if i != nil {
		pcuo.SetPsMessage(*i)
	}
	return pcuo
}

// AddPsMessage adds i to the "ps_message" field.
func (pcuo *PsConfigUpdateOne) AddPsMessage(i int) *PsConfigUpdateOne {
	pcuo.mutation.AddPsMessage(i)
	return pcuo
}

// ClearPsMessage clears the value of the "ps_message" field.
func (pcuo *PsConfigUpdateOne) ClearPsMessage() *PsConfigUpdateOne {
	pcuo.mutation.ClearPsMessage()
	return pcuo
}

// SetPsEvent sets the "ps_event" field.
func (pcuo *PsConfigUpdateOne) SetPsEvent(i int) *PsConfigUpdateOne {
	pcuo.mutation.ResetPsEvent()
	pcuo.mutation.SetPsEvent(i)
	return pcuo
}

// SetNillablePsEvent sets the "ps_event" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillablePsEvent(i *int) *PsConfigUpdateOne {
	if i != nil {
		pcuo.SetPsEvent(*i)
	}
	return pcuo
}

// AddPsEvent adds i to the "ps_event" field.
func (pcuo *PsConfigUpdateOne) AddPsEvent(i int) *PsConfigUpdateOne {
	pcuo.mutation.AddPsEvent(i)
	return pcuo
}

// ClearPsEvent clears the value of the "ps_event" field.
func (pcuo *PsConfigUpdateOne) ClearPsEvent() *PsConfigUpdateOne {
	pcuo.mutation.ClearPsEvent()
	return pcuo
}

// SetPsFeature sets the "ps_feature" field.
func (pcuo *PsConfigUpdateOne) SetPsFeature(i int) *PsConfigUpdateOne {
	pcuo.mutation.ResetPsFeature()
	pcuo.mutation.SetPsFeature(i)
	return pcuo
}

// SetNillablePsFeature sets the "ps_feature" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillablePsFeature(i *int) *PsConfigUpdateOne {
	if i != nil {
		pcuo.SetPsFeature(*i)
	}
	return pcuo
}

// AddPsFeature adds i to the "ps_feature" field.
func (pcuo *PsConfigUpdateOne) AddPsFeature(i int) *PsConfigUpdateOne {
	pcuo.mutation.AddPsFeature(i)
	return pcuo
}

// ClearPsFeature clears the value of the "ps_feature" field.
func (pcuo *PsConfigUpdateOne) ClearPsFeature() *PsConfigUpdateOne {
	pcuo.mutation.ClearPsFeature()
	return pcuo
}

// SetPsStrategy sets the "ps_strategy" field.
func (pcuo *PsConfigUpdateOne) SetPsStrategy(i int) *PsConfigUpdateOne {
	pcuo.mutation.ResetPsStrategy()
	pcuo.mutation.SetPsStrategy(i)
	return pcuo
}

// SetNillablePsStrategy sets the "ps_strategy" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillablePsStrategy(i *int) *PsConfigUpdateOne {
	if i != nil {
		pcuo.SetPsStrategy(*i)
	}
	return pcuo
}

// AddPsStrategy adds i to the "ps_strategy" field.
func (pcuo *PsConfigUpdateOne) AddPsStrategy(i int) *PsConfigUpdateOne {
	pcuo.mutation.AddPsStrategy(i)
	return pcuo
}

// ClearPsStrategy clears the value of the "ps_strategy" field.
func (pcuo *PsConfigUpdateOne) ClearPsStrategy() *PsConfigUpdateOne {
	pcuo.mutation.ClearPsStrategy()
	return pcuo
}

// SetOwnerID sets the "owner_id" field.
func (pcuo *PsConfigUpdateOne) SetOwnerID(i int) *PsConfigUpdateOne {
	pcuo.mutation.ResetOwnerID()
	pcuo.mutation.SetOwnerID(i)
	return pcuo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillableOwnerID(i *int) *PsConfigUpdateOne {
	if i != nil {
		pcuo.SetOwnerID(*i)
	}
	return pcuo
}

// AddOwnerID adds i to the "owner_id" field.
func (pcuo *PsConfigUpdateOne) AddOwnerID(i int) *PsConfigUpdateOne {
	pcuo.mutation.AddOwnerID(i)
	return pcuo
}

// ClearOwnerID clears the value of the "owner_id" field.
func (pcuo *PsConfigUpdateOne) ClearOwnerID() *PsConfigUpdateOne {
	pcuo.mutation.ClearOwnerID()
	return pcuo
}

// SetManagers sets the "managers" field.
func (pcuo *PsConfigUpdateOne) SetManagers(s string) *PsConfigUpdateOne {
	pcuo.mutation.SetManagers(s)
	return pcuo
}

// SetNillableManagers sets the "managers" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillableManagers(s *string) *PsConfigUpdateOne {
	if s != nil {
		pcuo.SetManagers(*s)
	}
	return pcuo
}

// ClearManagers clears the value of the "managers" field.
func (pcuo *PsConfigUpdateOne) ClearManagers() *PsConfigUpdateOne {
	pcuo.mutation.ClearManagers()
	return pcuo
}

// SetUpdateUser sets the "update_user" field.
func (pcuo *PsConfigUpdateOne) SetUpdateUser(i int) *PsConfigUpdateOne {
	pcuo.mutation.ResetUpdateUser()
	pcuo.mutation.SetUpdateUser(i)
	return pcuo
}

// SetNillableUpdateUser sets the "update_user" field if the given value is not nil.
func (pcuo *PsConfigUpdateOne) SetNillableUpdateUser(i *int) *PsConfigUpdateOne {
	if i != nil {
		pcuo.SetUpdateUser(*i)
	}
	return pcuo
}

// AddUpdateUser adds i to the "update_user" field.
func (pcuo *PsConfigUpdateOne) AddUpdateUser(i int) *PsConfigUpdateOne {
	pcuo.mutation.AddUpdateUser(i)
	return pcuo
}

// ClearUpdateUser clears the value of the "update_user" field.
func (pcuo *PsConfigUpdateOne) ClearUpdateUser() *PsConfigUpdateOne {
	pcuo.mutation.ClearUpdateUser()
	return pcuo
}

// Mutation returns the PsConfigMutation object of the builder.
func (pcuo *PsConfigUpdateOne) Mutation() *PsConfigMutation {
	return pcuo.mutation
}

// Where appends a list predicates to the PsConfigUpdate builder.
func (pcuo *PsConfigUpdateOne) Where(ps ...predicate.PsConfig) *PsConfigUpdateOne {
	pcuo.mutation.Where(ps...)
	return pcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pcuo *PsConfigUpdateOne) Select(field string, fields ...string) *PsConfigUpdateOne {
	pcuo.fields = append([]string{field}, fields...)
	return pcuo
}

// Save executes the query and returns the updated PsConfig entity.
func (pcuo *PsConfigUpdateOne) Save(ctx context.Context) (*PsConfig, error) {
	pcuo.defaults()
	return withHooks(ctx, pcuo.sqlSave, pcuo.mutation, pcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pcuo *PsConfigUpdateOne) SaveX(ctx context.Context) *PsConfig {
	node, err := pcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pcuo *PsConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := pcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcuo *PsConfigUpdateOne) ExecX(ctx context.Context) {
	if err := pcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcuo *PsConfigUpdateOne) defaults() {
	if _, ok := pcuo.mutation.UpdateTime(); !ok {
		v := psconfig.UpdateDefaultUpdateTime()
		pcuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcuo *PsConfigUpdateOne) check() error {
	if v, ok := pcuo.mutation.PsScene(); ok {
		if err := psconfig.PsSceneValidator(v); err != nil {
			return &ValidationError{Name: "ps_scene", err: fmt.Errorf(`ent: validator failed for field "PsConfig.ps_scene": %w`, err)}
		}
	}
	return nil
}

func (pcuo *PsConfigUpdateOne) sqlSave(ctx context.Context) (_node *PsConfig, err error) {
	if err := pcuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(psconfig.Table, psconfig.Columns, sqlgraph.NewFieldSpec(psconfig.FieldID, field.TypeInt))
	id, ok := pcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PsConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, psconfig.FieldID)
		for _, f := range fields {
			if !psconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != psconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcuo.mutation.UpdateTime(); ok {
		_spec.SetField(psconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pcuo.mutation.PsScene(); ok {
		_spec.SetField(psconfig.FieldPsScene, field.TypeString, value)
	}
	if value, ok := pcuo.mutation.PsFilter(); ok {
		_spec.SetField(psconfig.FieldPsFilter, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.AddedPsFilter(); ok {
		_spec.AddField(psconfig.FieldPsFilter, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.PsMessage(); ok {
		_spec.SetField(psconfig.FieldPsMessage, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.AddedPsMessage(); ok {
		_spec.AddField(psconfig.FieldPsMessage, field.TypeInt, value)
	}
	if pcuo.mutation.PsMessageCleared() {
		_spec.ClearField(psconfig.FieldPsMessage, field.TypeInt)
	}
	if value, ok := pcuo.mutation.PsEvent(); ok {
		_spec.SetField(psconfig.FieldPsEvent, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.AddedPsEvent(); ok {
		_spec.AddField(psconfig.FieldPsEvent, field.TypeInt, value)
	}
	if pcuo.mutation.PsEventCleared() {
		_spec.ClearField(psconfig.FieldPsEvent, field.TypeInt)
	}
	if value, ok := pcuo.mutation.PsFeature(); ok {
		_spec.SetField(psconfig.FieldPsFeature, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.AddedPsFeature(); ok {
		_spec.AddField(psconfig.FieldPsFeature, field.TypeInt, value)
	}
	if pcuo.mutation.PsFeatureCleared() {
		_spec.ClearField(psconfig.FieldPsFeature, field.TypeInt)
	}
	if value, ok := pcuo.mutation.PsStrategy(); ok {
		_spec.SetField(psconfig.FieldPsStrategy, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.AddedPsStrategy(); ok {
		_spec.AddField(psconfig.FieldPsStrategy, field.TypeInt, value)
	}
	if pcuo.mutation.PsStrategyCleared() {
		_spec.ClearField(psconfig.FieldPsStrategy, field.TypeInt)
	}
	if value, ok := pcuo.mutation.OwnerID(); ok {
		_spec.SetField(psconfig.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.AddedOwnerID(); ok {
		_spec.AddField(psconfig.FieldOwnerID, field.TypeInt, value)
	}
	if pcuo.mutation.OwnerIDCleared() {
		_spec.ClearField(psconfig.FieldOwnerID, field.TypeInt)
	}
	if value, ok := pcuo.mutation.Managers(); ok {
		_spec.SetField(psconfig.FieldManagers, field.TypeString, value)
	}
	if pcuo.mutation.ManagersCleared() {
		_spec.ClearField(psconfig.FieldManagers, field.TypeString)
	}
	if value, ok := pcuo.mutation.UpdateUser(); ok {
		_spec.SetField(psconfig.FieldUpdateUser, field.TypeInt, value)
	}
	if value, ok := pcuo.mutation.AddedUpdateUser(); ok {
		_spec.AddField(psconfig.FieldUpdateUser, field.TypeInt, value)
	}
	if pcuo.mutation.UpdateUserCleared() {
		_spec.ClearField(psconfig.FieldUpdateUser, field.TypeInt)
	}
	_node = &PsConfig{config: pcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{psconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pcuo.mutation.done = true
	return _node, nil
}
