// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mall/ent/psconfig"
	"mall/ent/psstrategy"
	"mall/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	psconfigMixin := schema.PsConfig{}.Mixin()
	psconfigMixinFields0 := psconfigMixin[0].Fields()
	_ = psconfigMixinFields0
	psconfigFields := schema.PsConfig{}.Fields()
	_ = psconfigFields
	// psconfigDescCreateTime is the schema descriptor for create_time field.
	psconfigDescCreateTime := psconfigMixinFields0[0].Descriptor()
	// psconfig.DefaultCreateTime holds the default value on creation for the create_time field.
	psconfig.DefaultCreateTime = psconfigDescCreateTime.Default.(func() time.Time)
	// psconfigDescUpdateTime is the schema descriptor for update_time field.
	psconfigDescUpdateTime := psconfigMixinFields0[1].Descriptor()
	// psconfig.DefaultUpdateTime holds the default value on creation for the update_time field.
	psconfig.DefaultUpdateTime = psconfigDescUpdateTime.Default.(func() time.Time)
	// psconfig.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	psconfig.UpdateDefaultUpdateTime = psconfigDescUpdateTime.UpdateDefault.(func() time.Time)
	// psconfigDescPsScene is the schema descriptor for ps_scene field.
	psconfigDescPsScene := psconfigFields[1].Descriptor()
	// psconfig.PsSceneValidator is a validator for the "ps_scene" field. It is called by the builders before save.
	psconfig.PsSceneValidator = psconfigDescPsScene.Validators[0].(func(string) error)
	// psconfigDescID is the schema descriptor for id field.
	psconfigDescID := psconfigFields[0].Descriptor()
	// psconfig.IDValidator is a validator for the "id" field. It is called by the builders before save.
	psconfig.IDValidator = psconfigDescID.Validators[0].(func(int) error)
	psstrategyMixin := schema.PsStrategy{}.Mixin()
	psstrategyMixinFields0 := psstrategyMixin[0].Fields()
	_ = psstrategyMixinFields0
	psstrategyFields := schema.PsStrategy{}.Fields()
	_ = psstrategyFields
	// psstrategyDescCreateTime is the schema descriptor for create_time field.
	psstrategyDescCreateTime := psstrategyMixinFields0[0].Descriptor()
	// psstrategy.DefaultCreateTime holds the default value on creation for the create_time field.
	psstrategy.DefaultCreateTime = psstrategyDescCreateTime.Default.(func() time.Time)
	// psstrategyDescUpdateTime is the schema descriptor for update_time field.
	psstrategyDescUpdateTime := psstrategyMixinFields0[1].Descriptor()
	// psstrategy.DefaultUpdateTime holds the default value on creation for the update_time field.
	psstrategy.DefaultUpdateTime = psstrategyDescUpdateTime.Default.(func() time.Time)
	// psstrategy.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	psstrategy.UpdateDefaultUpdateTime = psstrategyDescUpdateTime.UpdateDefault.(func() time.Time)
	// psstrategyDescIsDelete is the schema descriptor for is_delete field.
	psstrategyDescIsDelete := psstrategyFields[3].Descriptor()
	// psstrategy.DefaultIsDelete holds the default value on creation for the is_delete field.
	psstrategy.DefaultIsDelete = psstrategyDescIsDelete.Default.(int)
	// psstrategyDescID is the schema descriptor for id field.
	psstrategyDescID := psstrategyFields[0].Descriptor()
	// psstrategy.IDValidator is a validator for the "id" field. It is called by the builders before save.
	psstrategy.IDValidator = psstrategyDescID.Validators[0].(func(int) error)
}
