definitions:
  serializer.Response:
    properties:
      data: {}
      error:
        type: string
      msg:
        type: string
      status:
        type: integer
    type: object
  service.UserService:
    properties:
      key:
        description: 前端进行判断
        type: string
      nick_name:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get a list of products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: List products
      tags:
      - products
  /api/v1/ps_config/{id}:
    get:
      consumes:
      - application/json
      description: Get a single psConfig by ID
      parameters:
      - description: PsConfig ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: Get a psConfig
      tags:
      - psConfigs
  /api/v1/ps_configs:
    get:
      consumes:
      - application/json
      description: Get a list of psConfig
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: List psConfigs
      tags:
      - psConfigs
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a token
      parameters:
      - description: User login credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserService'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/serializer.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/serializer.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/serializer.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: User login
      tags:
      - users
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided information
      parameters:
      - description: User registration information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserService'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully registered
          schema:
            $ref: '#/definitions/serializer.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/serializer.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: Register a new user
      tags:
      - users
swagger: "2.0"
