// Code generated by ent, DO NOT EDIT.

package psconfig

import (
	"mall/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldUpdateTime, v))
}

// PsScene applies equality check predicate on the "ps_scene" field. It's identical to PsSceneEQ.
func PsScene(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsScene, v))
}

// PsFilter applies equality check predicate on the "ps_filter" field. It's identical to PsFilterEQ.
func PsFilter(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsFilter, v))
}

// PsMessage applies equality check predicate on the "ps_message" field. It's identical to PsMessageEQ.
func PsMessage(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsMessage, v))
}

// PsEvent applies equality check predicate on the "ps_event" field. It's identical to PsEventEQ.
func PsEvent(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsEvent, v))
}

// PsFeature applies equality check predicate on the "ps_feature" field. It's identical to PsFeatureEQ.
func PsFeature(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsFeature, v))
}

// PsStrategy applies equality check predicate on the "ps_strategy" field. It's identical to PsStrategyEQ.
func PsStrategy(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsStrategy, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldOwnerID, v))
}

// Managers applies equality check predicate on the "managers" field. It's identical to ManagersEQ.
func Managers(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldManagers, v))
}

// UpdateUser applies equality check predicate on the "update_user" field. It's identical to UpdateUserEQ.
func UpdateUser(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldUpdateUser, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldUpdateTime, v))
}

// PsSceneEQ applies the EQ predicate on the "ps_scene" field.
func PsSceneEQ(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsScene, v))
}

// PsSceneNEQ applies the NEQ predicate on the "ps_scene" field.
func PsSceneNEQ(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldPsScene, v))
}

// PsSceneIn applies the In predicate on the "ps_scene" field.
func PsSceneIn(vs ...string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldPsScene, vs...))
}

// PsSceneNotIn applies the NotIn predicate on the "ps_scene" field.
func PsSceneNotIn(vs ...string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldPsScene, vs...))
}

// PsSceneGT applies the GT predicate on the "ps_scene" field.
func PsSceneGT(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldPsScene, v))
}

// PsSceneGTE applies the GTE predicate on the "ps_scene" field.
func PsSceneGTE(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldPsScene, v))
}

// PsSceneLT applies the LT predicate on the "ps_scene" field.
func PsSceneLT(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldPsScene, v))
}

// PsSceneLTE applies the LTE predicate on the "ps_scene" field.
func PsSceneLTE(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldPsScene, v))
}

// PsSceneContains applies the Contains predicate on the "ps_scene" field.
func PsSceneContains(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldContains(FieldPsScene, v))
}

// PsSceneHasPrefix applies the HasPrefix predicate on the "ps_scene" field.
func PsSceneHasPrefix(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldHasPrefix(FieldPsScene, v))
}

// PsSceneHasSuffix applies the HasSuffix predicate on the "ps_scene" field.
func PsSceneHasSuffix(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldHasSuffix(FieldPsScene, v))
}

// PsSceneEqualFold applies the EqualFold predicate on the "ps_scene" field.
func PsSceneEqualFold(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEqualFold(FieldPsScene, v))
}

// PsSceneContainsFold applies the ContainsFold predicate on the "ps_scene" field.
func PsSceneContainsFold(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldContainsFold(FieldPsScene, v))
}

// PsFilterEQ applies the EQ predicate on the "ps_filter" field.
func PsFilterEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsFilter, v))
}

// PsFilterNEQ applies the NEQ predicate on the "ps_filter" field.
func PsFilterNEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldPsFilter, v))
}

// PsFilterIn applies the In predicate on the "ps_filter" field.
func PsFilterIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldPsFilter, vs...))
}

// PsFilterNotIn applies the NotIn predicate on the "ps_filter" field.
func PsFilterNotIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldPsFilter, vs...))
}

// PsFilterGT applies the GT predicate on the "ps_filter" field.
func PsFilterGT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldPsFilter, v))
}

// PsFilterGTE applies the GTE predicate on the "ps_filter" field.
func PsFilterGTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldPsFilter, v))
}

// PsFilterLT applies the LT predicate on the "ps_filter" field.
func PsFilterLT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldPsFilter, v))
}

// PsFilterLTE applies the LTE predicate on the "ps_filter" field.
func PsFilterLTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldPsFilter, v))
}

// PsMessageEQ applies the EQ predicate on the "ps_message" field.
func PsMessageEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsMessage, v))
}

// PsMessageNEQ applies the NEQ predicate on the "ps_message" field.
func PsMessageNEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldPsMessage, v))
}

// PsMessageIn applies the In predicate on the "ps_message" field.
func PsMessageIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldPsMessage, vs...))
}

// PsMessageNotIn applies the NotIn predicate on the "ps_message" field.
func PsMessageNotIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldPsMessage, vs...))
}

// PsMessageGT applies the GT predicate on the "ps_message" field.
func PsMessageGT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldPsMessage, v))
}

// PsMessageGTE applies the GTE predicate on the "ps_message" field.
func PsMessageGTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldPsMessage, v))
}

// PsMessageLT applies the LT predicate on the "ps_message" field.
func PsMessageLT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldPsMessage, v))
}

// PsMessageLTE applies the LTE predicate on the "ps_message" field.
func PsMessageLTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldPsMessage, v))
}

// PsMessageIsNil applies the IsNil predicate on the "ps_message" field.
func PsMessageIsNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIsNull(FieldPsMessage))
}

// PsMessageNotNil applies the NotNil predicate on the "ps_message" field.
func PsMessageNotNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotNull(FieldPsMessage))
}

// PsEventEQ applies the EQ predicate on the "ps_event" field.
func PsEventEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsEvent, v))
}

// PsEventNEQ applies the NEQ predicate on the "ps_event" field.
func PsEventNEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldPsEvent, v))
}

// PsEventIn applies the In predicate on the "ps_event" field.
func PsEventIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldPsEvent, vs...))
}

// PsEventNotIn applies the NotIn predicate on the "ps_event" field.
func PsEventNotIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldPsEvent, vs...))
}

// PsEventGT applies the GT predicate on the "ps_event" field.
func PsEventGT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldPsEvent, v))
}

// PsEventGTE applies the GTE predicate on the "ps_event" field.
func PsEventGTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldPsEvent, v))
}

// PsEventLT applies the LT predicate on the "ps_event" field.
func PsEventLT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldPsEvent, v))
}

// PsEventLTE applies the LTE predicate on the "ps_event" field.
func PsEventLTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldPsEvent, v))
}

// PsEventIsNil applies the IsNil predicate on the "ps_event" field.
func PsEventIsNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIsNull(FieldPsEvent))
}

// PsEventNotNil applies the NotNil predicate on the "ps_event" field.
func PsEventNotNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotNull(FieldPsEvent))
}

// PsFeatureEQ applies the EQ predicate on the "ps_feature" field.
func PsFeatureEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsFeature, v))
}

// PsFeatureNEQ applies the NEQ predicate on the "ps_feature" field.
func PsFeatureNEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldPsFeature, v))
}

// PsFeatureIn applies the In predicate on the "ps_feature" field.
func PsFeatureIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldPsFeature, vs...))
}

// PsFeatureNotIn applies the NotIn predicate on the "ps_feature" field.
func PsFeatureNotIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldPsFeature, vs...))
}

// PsFeatureGT applies the GT predicate on the "ps_feature" field.
func PsFeatureGT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldPsFeature, v))
}

// PsFeatureGTE applies the GTE predicate on the "ps_feature" field.
func PsFeatureGTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldPsFeature, v))
}

// PsFeatureLT applies the LT predicate on the "ps_feature" field.
func PsFeatureLT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldPsFeature, v))
}

// PsFeatureLTE applies the LTE predicate on the "ps_feature" field.
func PsFeatureLTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldPsFeature, v))
}

// PsFeatureIsNil applies the IsNil predicate on the "ps_feature" field.
func PsFeatureIsNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIsNull(FieldPsFeature))
}

// PsFeatureNotNil applies the NotNil predicate on the "ps_feature" field.
func PsFeatureNotNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotNull(FieldPsFeature))
}

// PsStrategyEQ applies the EQ predicate on the "ps_strategy" field.
func PsStrategyEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldPsStrategy, v))
}

// PsStrategyNEQ applies the NEQ predicate on the "ps_strategy" field.
func PsStrategyNEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldPsStrategy, v))
}

// PsStrategyIn applies the In predicate on the "ps_strategy" field.
func PsStrategyIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldPsStrategy, vs...))
}

// PsStrategyNotIn applies the NotIn predicate on the "ps_strategy" field.
func PsStrategyNotIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldPsStrategy, vs...))
}

// PsStrategyGT applies the GT predicate on the "ps_strategy" field.
func PsStrategyGT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldPsStrategy, v))
}

// PsStrategyGTE applies the GTE predicate on the "ps_strategy" field.
func PsStrategyGTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldPsStrategy, v))
}

// PsStrategyLT applies the LT predicate on the "ps_strategy" field.
func PsStrategyLT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldPsStrategy, v))
}

// PsStrategyLTE applies the LTE predicate on the "ps_strategy" field.
func PsStrategyLTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldPsStrategy, v))
}

// PsStrategyIsNil applies the IsNil predicate on the "ps_strategy" field.
func PsStrategyIsNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIsNull(FieldPsStrategy))
}

// PsStrategyNotNil applies the NotNil predicate on the "ps_strategy" field.
func PsStrategyNotNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotNull(FieldPsStrategy))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIsNull(FieldOwnerID))
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotNull(FieldOwnerID))
}

// ManagersEQ applies the EQ predicate on the "managers" field.
func ManagersEQ(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldManagers, v))
}

// ManagersNEQ applies the NEQ predicate on the "managers" field.
func ManagersNEQ(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldManagers, v))
}

// ManagersIn applies the In predicate on the "managers" field.
func ManagersIn(vs ...string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldManagers, vs...))
}

// ManagersNotIn applies the NotIn predicate on the "managers" field.
func ManagersNotIn(vs ...string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldManagers, vs...))
}

// ManagersGT applies the GT predicate on the "managers" field.
func ManagersGT(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldManagers, v))
}

// ManagersGTE applies the GTE predicate on the "managers" field.
func ManagersGTE(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldManagers, v))
}

// ManagersLT applies the LT predicate on the "managers" field.
func ManagersLT(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldManagers, v))
}

// ManagersLTE applies the LTE predicate on the "managers" field.
func ManagersLTE(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldManagers, v))
}

// ManagersContains applies the Contains predicate on the "managers" field.
func ManagersContains(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldContains(FieldManagers, v))
}

// ManagersHasPrefix applies the HasPrefix predicate on the "managers" field.
func ManagersHasPrefix(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldHasPrefix(FieldManagers, v))
}

// ManagersHasSuffix applies the HasSuffix predicate on the "managers" field.
func ManagersHasSuffix(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldHasSuffix(FieldManagers, v))
}

// ManagersIsNil applies the IsNil predicate on the "managers" field.
func ManagersIsNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIsNull(FieldManagers))
}

// ManagersNotNil applies the NotNil predicate on the "managers" field.
func ManagersNotNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotNull(FieldManagers))
}

// ManagersEqualFold applies the EqualFold predicate on the "managers" field.
func ManagersEqualFold(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEqualFold(FieldManagers, v))
}

// ManagersContainsFold applies the ContainsFold predicate on the "managers" field.
func ManagersContainsFold(v string) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldContainsFold(FieldManagers, v))
}

// UpdateUserEQ applies the EQ predicate on the "update_user" field.
func UpdateUserEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldEQ(FieldUpdateUser, v))
}

// UpdateUserNEQ applies the NEQ predicate on the "update_user" field.
func UpdateUserNEQ(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNEQ(FieldUpdateUser, v))
}

// UpdateUserIn applies the In predicate on the "update_user" field.
func UpdateUserIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIn(FieldUpdateUser, vs...))
}

// UpdateUserNotIn applies the NotIn predicate on the "update_user" field.
func UpdateUserNotIn(vs ...int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotIn(FieldUpdateUser, vs...))
}

// UpdateUserGT applies the GT predicate on the "update_user" field.
func UpdateUserGT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGT(FieldUpdateUser, v))
}

// UpdateUserGTE applies the GTE predicate on the "update_user" field.
func UpdateUserGTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldGTE(FieldUpdateUser, v))
}

// UpdateUserLT applies the LT predicate on the "update_user" field.
func UpdateUserLT(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLT(FieldUpdateUser, v))
}

// UpdateUserLTE applies the LTE predicate on the "update_user" field.
func UpdateUserLTE(v int) predicate.PsConfig {
	return predicate.PsConfig(sql.FieldLTE(FieldUpdateUser, v))
}

// UpdateUserIsNil applies the IsNil predicate on the "update_user" field.
func UpdateUserIsNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldIsNull(FieldUpdateUser))
}

// UpdateUserNotNil applies the NotNil predicate on the "update_user" field.
func UpdateUserNotNil() predicate.PsConfig {
	return predicate.PsConfig(sql.FieldNotNull(FieldUpdateUser))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PsConfig) predicate.PsConfig {
	return predicate.PsConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PsConfig) predicate.PsConfig {
	return predicate.PsConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PsConfig) predicate.PsConfig {
	return predicate.PsConfig(sql.NotPredicates(p))
}
